o1 = score.new_obj_by_name("linseg");
o1.set_prop("delay_update", 0);
o1.set_prop("aux_inputs", [  ]);
o1.set_prop("shape data", [ 60, 1, 80 ]);
o1.set_prop("transfer func", '');
o1.set_prop("height", 50);
o1.set_prop("max value", 80);
o1.set_prop("filled", 1);
o1.set_prop("start", 0);
o1.set_prop("proportional", 1);
o1.set_prop("ypos", 390);
o1.set_prop("linewidth", 1.5);
o1.set_prop("caption_enable", 1);
o1.set_prop("length", 49.9198);
o1.set_prop("base line", 60);
o1.set_prop("invert plot", 0);
o1.set_prop("labels", 1);
o1.set_prop("min value", 60);
o2 = score.new_obj_by_name("linseg");
o2.set_prop("delay_update", 0);
o2.set_prop("aux_inputs", [  ]);
o2.set_prop("shape data", [ 0, 3, 1, 2, 0 ]);
o2.set_prop("transfer func", '');
o2.set_prop("height", 50);
o2.set_prop("max value", 1);
o2.set_prop("filled", 1);
o2.set_prop("start", 0);
o2.set_prop("proportional", 1);
o2.set_prop("ypos", 330);
o2.set_prop("linewidth", 1.5);
o2.set_prop("caption_enable", 1);
o2.set_prop("length", 48.9625);
o2.set_prop("base line", 0);
o2.set_prop("invert plot", 0);
o2.set_prop("labels", 1);
o2.set_prop("min value", 0);
o3 = score.new_obj_by_name("datagen");
o3.set_prop("delay_update", 0);
o3.set_prop("aux_inputs", [ 'A', 'B', 'C' ]);
o3.set_prop("start", 0);
o3.set_prop("ypos", -50);
o3.set_prop("caption_enable", 1);
o3.set_prop("length", 49.9198);
o3.set_prop("text", 'seed = 48;
n = 56;
maxdur = 20;
mindur = 5;
math.seed(seed);
v = setsize([], n);
forindex(i;v) {
    t = i/n * length;
    ins = 5;
    ftab = 1;
    note = int(math.rand2(50, in.B(t)));
    frq = 440 * math.pow(2, (note-69) / 6);
    amp = 0.2 + math.rand() * in.A(t);
    dur = math.rand2(mindur, maxdur);
    v[i] = [t, [ins, dur, frq, amp, ftab]];
}
out.data = v;
');
o3.set_prop("font_size", 8);
o3.set_prop("alt_score_text", '');
o3.query_inlets();
c = o3.connect(o2,"out","A",26.48026498243063);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
c = o3.connect(o1,"out","B",24.43344791976109);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
o5 = score.new_obj_by_name("evgraph");
o5.set_prop("delay_update", 0);
o5.set_prop("size_scale", 10);
o5.set_prop("grid", 440);
o5.set_prop("black_parm", 3);
o5.set_prop("size_parm", 3);
o5.set_prop("height", 140);
o5.set_prop("start", 0);
o5.set_prop("ypos", 143);
o5.set_prop("caption_enable", 1);
o5.set_prop("y_parm", 2);
o5.set_prop("dur_parm", 1);
o5.set_prop("length", 68.5842);
o5.query_inlets();
c = o5.connect(o3,"out","events",33.18833644337366);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
o0 = score.new_obj_by_name("cs_ftab");
o0.set_prop("delay_update", 0);
o0.set_prop("height", 50);
o0.set_prop("parms", [ 1, 0, 1024, 7, 0, 450, 1, 124, -1, 450, 0 ]);
o0.set_prop("start", 0);
o0.set_prop("caption_enable", 1);
o0.set_prop("ypos", 465);
o0.set_prop("width", 200);
o4 = score.new_obj_by_name("csound_bus");
o4.set_prop("delay_update", 0);
o4.set_prop("amp", 1);
o4.set_prop("caption_enable", 1);
o4.set_prop("ypos", 300);
o4.set_prop("orc_file", 'test.orc');
o4.query_inlets();
c = o4.connect(o3,"out","events",35.77641772565509);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
c = o4.connect(o0,"out","ftable",3.636854166666667);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
o2.add_link(o3,0);
score.marks = [ { type : 'end', time : 68.5842 } ];
score.metadata = { composer : '', title : '', subtitle : '' };
