o4 = score.new_obj_by_name("shape");
o4.set_prop("delay_update", 0);
o4.set_prop("shape data", [ 0, 1 ]);
o4.set_prop("filled", 0);
o4.set_prop("height", 50);
o4.set_prop("max value", 1);
o4.set_prop("start", 0);
o4.set_prop("linewidth", 1);
o4.set_prop("ypos", 480);
o4.set_prop("caption_enable", 1);
o4.set_prop("base line", 0);
o4.set_prop("length", 7.00437);
o4.set_prop("labels", 1);
o4.set_prop("invert plot", 0);
o4.set_prop("min value", 0);
o5 = score.new_obj_by_name("sine");
o5.set_prop("out.resolution", 0.02);
o5.set_prop("delay_update", 0);
o5.set_prop("out.amp", 1);
o5.set_prop("filled", 0);
o5.set_prop("height", 50);
o5.set_prop("max value", 1);
o5.set_prop("start", 0);
o5.set_prop("linewidth", 1);
o5.set_prop("ypos", 405);
o5.set_prop("caption_enable", 1);
o5.set_prop("base line", 0);
o5.set_prop("length", 7.00437);
o5.set_prop("labels", 1);
o5.set_prop("invert plot", 0);
o5.set_prop("out.freq", 5);
o5.set_prop("min value", -1);
o5.query_inlets();
c = o5.connect(o4,"out","freq_mul",1.494587781921216);
c.set_prop("transfer func", 'math.pow(x,3)');
c.set_prop("hide_inlet", 0);
o6 = score.new_obj_by_name("datagen");
o6.set_prop("delay_update", 0);
o6.set_prop("start", 0);
o6.set_prop("ypos", 0);
o6.set_prop("caption_enable", 1);
o6.set_prop("length", 14.2127);
o6.set_prop("alt_score_text", '');
o6.set_prop("font_size", 8);
o6.set_prop("text", 'out.resolution = 0;
out.interpolate = 0;
out.data = setsize([], 100);

math.seed(123);

forindex(i; out.data) {
  t = math.rand2(0, length);     # randomize event start time
  n = math.irand2(20, 100);      # randomize note
  v = 20 + math.linrand() * 100; # randomize velocity
  d = math.linrand() + 0.1;      # randomize duration
  out.data[i] = [t, [n, v, d]];  # create the event
}
');
o6.query_inlets();
o7 = score.new_obj_by_name("evgraph");
o7.set_prop("delay_update", 0);
o7.set_prop("size_scale", 0.02);
o7.set_prop("grid", 12);
o7.set_prop("black_parm", nil);
o7.set_prop("size_parm", 1);
o7.set_prop("height", 100);
o7.set_prop("start", 0);
o7.set_prop("ypos", 160);
o7.set_prop("caption_enable", 1);
o7.set_prop("y_parm", 0);
o7.set_prop("dur_parm", 2);
o7.set_prop("length", 14.2127);
o7.query_inlets();
c = o7.connect(o6,"out","events",2.5);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
o2 = score.new_obj_by_name("shape");
o2.set_prop("delay_update", 0);
o2.set_prop("shape data", [ 0, -1, 1, 0 ]);
o2.set_prop("filled", 0);
o2.set_prop("height", 50);
o2.set_prop("max value", 1);
o2.set_prop("start", 0.63759);
o2.set_prop("linewidth", 1);
o2.set_prop("ypos", 330);
o2.set_prop("caption_enable", 1);
o2.set_prop("base line", 0);
o2.set_prop("length", 5.64969);
o2.set_prop("labels", 1);
o2.set_prop("invert plot", 0);
o2.set_prop("min value", -1);
o3 = score.new_obj_by_name("noise");
o3.set_prop("out.resolution", 0.1);
o3.set_prop("delay_update", 0);
o3.set_prop("out.interpolate", 0);
o3.set_prop("seed", 1.19673e+09);
o3.set_prop("filled", 0);
o3.set_prop("height", 50);
o3.set_prop("max value", 1);
o3.set_prop("start", 7.00437);
o3.set_prop("linewidth", 1);
o3.set_prop("ypos", 330);
o3.set_prop("caption_enable", 1);
o3.set_prop("base line", 0);
o3.set_prop("length", 7);
o3.set_prop("labels", 1);
o3.set_prop("invert plot", 0);
o3.set_prop("min value", -1);
o3.query_inlets();
o0 = score.new_obj_by_name("shape");
o0.set_prop("delay_update", 0);
o0.set_prop("shape data", [ 0, 1, 0 ]);
o0.set_prop("filled", 0);
o0.set_prop("height", 50);
o0.set_prop("max value", 1);
o0.set_prop("start", 7.86774);
o0.set_prop("linewidth", 1);
o0.set_prop("ypos", 480);
o0.set_prop("caption_enable", 1);
o0.set_prop("base line", 0);
o0.set_prop("length", 5.08678);
o0.set_prop("labels", 1);
o0.set_prop("invert plot", 0);
o0.set_prop("min value", 0);
o1 = score.new_obj_by_name("sine");
o1.set_prop("out.resolution", 0.02);
o1.set_prop("delay_update", 0);
o1.set_prop("out.amp", 1);
o1.set_prop("filled", 0);
o1.set_prop("height", 50);
o1.set_prop("max value", 1);
o1.set_prop("start", 7.86774);
o1.set_prop("linewidth", 1);
o1.set_prop("ypos", 405);
o1.set_prop("caption_enable", 1);
o1.set_prop("base line", 0);
o1.set_prop("length", 5.08678);
o1.set_prop("labels", 1);
o1.set_prop("invert plot", 0);
o1.set_prop("out.freq", 2);
o1.set_prop("min value", -1);
o1.query_inlets();
c = o1.connect(o0,"out","amp",2.537979252319046);
c.set_prop("transfer func", 'math.pow(x,2)');
c.set_prop("hide_inlet", 0);
o8 = score.new_obj_by_name("midi_bus");
o8.set_prop("delay_update", 0);
o8.set_prop("port_id", 'midi_0');
o8.set_prop("resolution", 0.01);
o8.set_prop("ypos", 285);
o8.set_prop("caption_enable", 1);
o8.set_prop("channel", 1);
o8.set_prop("controllers", { vol : 7 });
o8.query_inlets();
c = o8.connect(o6,"out","note",3.660714285714285);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
c = o8.connect(o2,"out","pitch",2.631754321936865);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
c = o8.connect(o1,"out","pitch",9.841719545103857);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
c = o8.connect(o3,"out","vol",8.671429112090074);
c.set_prop("transfer func", '(x+1)/2');
c.set_prop("hide_inlet", 0);
c = o8.connect(o5,"out","vol",1.315877160968433);
c.set_prop("transfer func", '(x+1)/2');
c.set_prop("hide_inlet", 0);
o0.add_link(o1,0);
o3.add_link(o5,0);
o4.add_link(o5,0);
score.marks = [ { type : 'end', time : 14.4643 } ];
score.metadata = { composer : '', title : '', subtitle : '' };
