o4 = score.new_obj_by_name("comment");
o4.set_prop("marker in score", 0);
o4.set_prop("caption_enable", 1);
o4.set_prop("delay_update", 0);
o4.set_prop("text", 'Example to control separate csound running osc_test.csd');
o4.set_prop("start", 0);
o4.set_prop("marker direction", 0);
o4.set_prop("ypos", 210);
o4.set_prop("font_size", 10);
o2 = score.new_obj_by_name("jitter");
o2.set_prop("end value", 0);
o2.set_prop("aux_inputs", [  ]);
o2.set_prop("transfer func", 'math.pow(x,0.5)');
o2.set_prop("filled", 1);
o2.set_prop("height", 50);
o2.set_prop("length", 25.5391);
o2.set_prop("base line", 0);
o2.set_prop("caption_enable", 1);
o2.set_prop("max duration", 0.4);
o2.set_prop("min value", 0);
o2.set_prop("delay_update", 0);
o2.set_prop("linewidth", 1);
o2.set_prop("time_randomizer", 'math.rand()*(max-min)+min');
o2.set_prop("labels", 0);
o2.set_prop("invert plot", 0);
o2.set_prop("start", 0);
o2.set_prop("seed", 42);
o2.set_prop("max value", 1);
o2.set_prop("value_randomizer", 'math.rand()*(max-0.2)+0.2');
o2.set_prop("ypos", 465);
o2.set_prop("start value", 0);
o2.set_prop("min duration", 0);
o2.query_inlets();
o1 = score.new_obj_by_name("jitter");
o1.set_prop("end value", 0);
o1.set_prop("aux_inputs", [  ]);
o1.set_prop("transfer func", 'math.mod(x*3,1)');
o1.set_prop("filled", 1);
o1.set_prop("height", 50);
o1.set_prop("length", 25.5391);
o1.set_prop("base line", 0);
o1.set_prop("caption_enable", 1);
o1.set_prop("max duration", 0.5);
o1.set_prop("min value", 0);
o1.set_prop("delay_update", 0);
o1.set_prop("linewidth", 1);
o1.set_prop("time_randomizer", 'math.rand()*(max-min)+min');
o1.set_prop("labels", 0);
o1.set_prop("invert plot", 0);
o1.set_prop("start", 0);
o1.set_prop("seed", 56);
o1.set_prop("max value", 1);
o1.set_prop("value_randomizer", 'math.rand()*(max-min)+min');
o1.set_prop("ypos", 255);
o1.set_prop("start value", 0);
o1.set_prop("min duration", 0.1);
o1.query_inlets();
o0 = score.new_obj_by_name("jitter");
o0.set_prop("end value", 0);
o0.set_prop("aux_inputs", [  ]);
o0.set_prop("transfer func", '');
o0.set_prop("filled", 1);
o0.set_prop("height", 50);
o0.set_prop("length", 25.5391);
o0.set_prop("base line", 0);
o0.set_prop("caption_enable", 1);
o0.set_prop("max duration", 1);
o0.set_prop("min value", 0);
o0.set_prop("delay_update", 0);
o0.set_prop("linewidth", 1);
o0.set_prop("time_randomizer", 'math.rand()*(max-min)+min');
o0.set_prop("labels", 0);
o0.set_prop("invert plot", 0);
o0.set_prop("start", 0);
o0.set_prop("seed", 88);
o0.set_prop("max value", 1);
o0.set_prop("value_randomizer", 'math.rand()*(max-0.2)+0.2');
o0.set_prop("ypos", 390);
o0.set_prop("start value", 0.5);
o0.set_prop("min duration", 0.1);
o0.query_inlets();
o3 = score.new_obj_by_name("osc_bus");
o3.set_prop("controllers", { freq : [ '/freq', 'f' ], amp : [ '/amp', 'f' ], pw : [ '/pw', 'f' ] });
o3.set_prop("resolution", 0.02);
o3.set_prop("caption_enable", 1);
o3.set_prop("delay_update", 0);
o3.set_prop("ypos", 345);
o3.set_prop("osc_address", 'osc.udp://localhost:7770');
o3.query_inlets();
c = o3.connect(o2,"out","amp",12.6171875);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
c = o3.connect(o1,"out","freq",10.17578125);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
c = o3.connect(o0,"out","pw",19.0625);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
score.marks = [ { type : 'end', time : 25.8984 } ];
score.metadata = { composer : '', subtitle : '', title : '' };
