o2 = score.new_obj_by_name("jitter");
o2.set_prop("delay_update", 0);
o2.set_prop("aux_inputs", [  ]);
o2.set_prop("transfer func", '');
o2.set_prop("min duration", 0);
o2.set_prop("seed", 32);
o2.set_prop("height", 50);
o2.set_prop("max value", 1);
o2.set_prop("filled", 0);
o2.set_prop("start", 0);
o2.set_prop("ypos", 75);
o2.set_prop("linewidth", 1);
o2.set_prop("caption_enable", 1);
o2.set_prop("max duration", 1);
o2.set_prop("end value", 0);
o2.set_prop("length", 14.4419);
o2.set_prop("base line", 0);
o2.set_prop("invert plot", 0);
o2.set_prop("labels", 0);
o2.set_prop("start value", 0);
o2.set_prop("min value", 0);
o2.query_inlets();
o0 = score.new_obj_by_name("linseg");
o0.set_prop("delay_update", 0);
o0.set_prop("aux_inputs", [  ]);
o0.set_prop("shape data", [ 0, 2, 1, 4, 1, 2, 0 ]);
o0.set_prop("transfer func", '');
o0.set_prop("height", 50);
o0.set_prop("max value", 1);
o0.set_prop("filled", 0);
o0.set_prop("start", 0);
o0.set_prop("proportional", 1);
o0.set_prop("ypos", 450);
o0.set_prop("linewidth", 1);
o0.set_prop("caption_enable", 1);
o0.set_prop("length", 14.4419);
o0.set_prop("base line", 0);
o0.set_prop("invert plot", 0);
o0.set_prop("labels", 1);
o0.set_prop("min value", 0);
o1 = score.new_obj_by_name("signal_bus");
o1.set_prop("delay_update", 0);
o1.set_prop("port_id", 'signal_amp');
o1.set_prop("caption_enable", 1);
o1.set_prop("ypos", 375);
o1.set_prop("sr_div", 100);
o1.query_inlets();
c = o1.connect(o0,"out","in",7.213356019489471);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
o3 = score.new_obj_by_name("linseg");
o3.set_prop("delay_update", 0);
o3.set_prop("aux_inputs", [  ]);
o3.set_prop("shape data", [ 0.2, 10, 20, 2, 2 ]);
o3.set_prop("transfer func", '');
o3.set_prop("height", 50);
o3.set_prop("max value", 20);
o3.set_prop("filled", 0);
o3.set_prop("start", 0.634213);
o3.set_prop("proportional", 1);
o3.set_prop("ypos", 285);
o3.set_prop("linewidth", 1);
o3.set_prop("caption_enable", 1);
o3.set_prop("length", 11.0766);
o3.set_prop("base line", 0);
o3.set_prop("invert plot", 0);
o3.set_prop("labels", 1);
o3.set_prop("min value", 0);
o4 = score.new_obj_by_name("sine");
o4.set_prop("out.resolution", 0.01);
o4.set_prop("delay_update", 0);
o4.set_prop("aux_inputs", [  ]);
o4.set_prop("out.amp", 1);
o4.set_prop("transfer func", '');
o4.set_prop("height", 50);
o4.set_prop("max value", 1);
o4.set_prop("filled", 0);
o4.set_prop("start", 0);
o4.set_prop("ypos", 195);
o4.set_prop("linewidth", 1);
o4.set_prop("caption_enable", 1);
o4.set_prop("length", 14.1434);
o4.set_prop("base line", 0);
o4.set_prop("invert plot", 0);
o4.set_prop("labels", 1);
o4.set_prop("min value", -1);
o4.set_prop("out.freq", 2);
o4.query_inlets();
c = o4.connect(o2,"out","amp",7.064114170810377);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
c = o4.connect(o3,"out","freq",5.986256374794709);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
o5 = score.new_obj_by_name("signal_bus");
o5.set_prop("delay_update", 0);
o5.set_prop("port_id", 'signal_freq');
o5.set_prop("caption_enable", 1);
o5.set_prop("ypos", 360);
o5.set_prop("sr_div", 50);
o5.query_inlets();
c = o5.connect(o4,"out","in",6.682971522453449);
c.set_prop("transfer func", '500+x*300');
c.set_prop("hide_inlet", 0);
score.marks = [ { type : 'end', time : 14.493 } ];
score.metadata = { title : '', composer : '', subtitle : '' };
