#!/bin/sh
DESTDIR="../../Help"
function DocSed {
    echo > $2
    sed -n 's/^#:: \(.*\)/\1/p;s/^#::[ \t]*$/\n/p' $1 >> $2
}

DocSed ../../lib/algoscore.nas baseclasses.inc

txt2tags -t xhtml -o algoscore-manual.html main.t2t
txt2tags -t xhtml --no-style -o algoscore-manual-plain.html main.t2t
mv algoscore-manual*.html $DESTDIR
cd $DESTDIR
htmldoc -f algoscore-manual.pdf -t pdf14 --browserwidth 800 --size a4 \
algoscore-manual-plain.html && rm algoscore-manual-plain.html
