#!/bin/sh

VERSION=`date +%y%m%d`

echo "AlgoScore $VERSION"

cd doc
echo "Generating docs..."
make_html

cd ../macosx/algoscore
#cd macosx
echo "Setting version in Info.plist..."
sed "s|%VERSION%|${VERSION}|g" Info.plist.in > Info.plist

cd ../../../Help
echo "Adding version to ChangeLog..."

echo -e "${VERSION}:\n" > ChangeLog.new
cat ChangeLog >> ChangeLog.new && mv -f ChangeLog.new ChangeLog

#echo "Stripping executable..."
#strip algoscore

cd ../..
echo "Packing tarball..."

tar -X AlgoScore/src/tarball.exclude -cjf AlgoScore-${VERSION}.tar.bz2 AlgoScore

echo "Done!"

