o1 = score.new_obj_by_name("sndfile");
o1.set_prop("height", 10);
o1.set_prop("start", 0);
o1.set_prop("caption_enable", 1);
o1.set_prop("ypos", 330);
o1.set_prop("sndfile", '/Users/lijon/brus.wav');
o1.set_prop("length", 5);
o0 = score.new_obj_by_name("audiobus");
o0.set_prop("amp", 1);
o0.set_prop("channels", 2);
o0.set_prop("port_id", 'audio_0');
o0.set_prop("caption_enable", 1);
o0.set_prop("ypos", 270);
o0.query_inlets();
c = o0.connect(o1,"out","in",2.498630561569689);
c.set_prop("transfer func", '');
c.set_prop("hide_inlet", 0);
score.marks = [ { type : 'end', time : 30 } ];
score.metadata = { composer : '', title : '', subtitle : '' };
